### ISSUE TITLE
[BUG] Importing and Searching Doesn't Seem To Work

### ISSUE THREAD

**Issue by Fewdys** [yobson1/FavCat-Restored#2] opened 2022-06-06 20:13 UTC
The Process Of Importing It Goes Through Seems To Work Just Doesn't Actually Import The List (Only Tested With A Text File)
As For The Local Search I Go and Log Avi's and Try Searching For Anything That Got Logged Or I Switched To and I Get No Results.

Edit: Clearing The Local Search Also Seems To Broken

**Comment by yobson1** [comment] 2022-06-06 22:06
Was able to reproduce and fix the avatar importing issue, will be included in the next release.
As for local searching/local search clear not working I'm unable to reproduce this. Are there any errors produced by FavCat when attempting to local search or clear the search?

**Closed as completed** 2022-06-08 07:29 UTC
Labels: bug
